name: 🎨 Chromatic Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'projects/design-system/**'
      - '.storybook/**'
      - 'package.json'
  pull_request:
    paths:
      - 'projects/design-system/**'
      - '.storybook/**'
      - 'package.json'
  workflow_dispatch:

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

env:
  CI: true
  HUSKY: 0

permissions:
  contents: read
  pull-requests: write

jobs:
  chromatic-deployment:
    name: 🚀 Deploy to Chromatic
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.6.5

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14
          cache: 'pnpm'

      - name: ⚡ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🔍 Check environment
        run: pnpm run check-env

      - name: 📝 Type checking
        run: pnpm run typecheck

      - name: 🏗️ Build Design System CSS
        run: pnpm run build:design-system:css

      - name: 🎨 Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: 'build:storybook'
          exitZeroOnChanges: true
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          onlyChanged: true

      - name: 🎉 Deployment summary
        run: |
          echo ""
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "🎉 Storybook deployed to Chromatic!"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo ""
          echo "✅ Visual tests completed"
          echo "📚 Storybook published"
          echo ""
